name: flu2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.20.2
  flutter_speed_dial: ^7.0.0
  mobile_scanner: ^7.1.2
  image_picker: ^1.0.4
  file_picker: ^10.3.3
  shared_preferences: ^2.2.2
  lottie: ^3.3.2
  flutter_image: ^4.1.13
  google_mlkit_text_recognition: ^0.15.0
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.3.2
  flutter_staggered_grid_view: ^0.7.0
  rive: ^0.13.20
  tflite_flutter: ^0.12.1
  crypto: ^3.0.3
  flutter_staggered_animations: ^1.1.1
  image_cropper: ^11.0.0
  flutter_image_compress: ^2.1.0
  pdf: ^3.10.8
  printing: ^5.11.1
  image: ^4.5.4
  camera: ^0.11.2
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.8
  qr_code_tools: ^0.2.0
  google_mlkit_barcode_scanning: ^0.14.1
  open_filex: ^4.0.3
  share_plus: ^10.0.0
  hugeicons: ^1.1.1
  uicons_pro: ^1.1.0
  device_info_plus: ^10.1.0
  network_info_plus: ^5.0.3
  flutter_keyboard_visibility: ^6.0.0
  pdfx: ^2.9.2
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1
  lucide_icons: ^0.257.0
  phosphor_flutter: ^2.1.0
  iconsax: ^0.0.8
  iconify_flutter: ^0.0.5
  iconly: ^1.0.1
  flutter_tabler_icons: ^1.37.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/f.png
    - assets/riv/moneda.riv
    - assets/riv/load.riv
    - assets/icon/doc.png
    - assets/riv/cargando2.riv
    - assets/riv/doc.riv
    - assets/icon/doc1.png
    - assets/icon/auditoria.png
    - assets/icon/informe1.png
    - assets/gifs/Individual.gif
    - assets/gifs/lock.gif
    - assets/img/interandina.jpg
    - assets/img/santaazul.jpg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900

    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Black.ttf
          weight: 700
        - asset: assets/fonts/FiraSans-Italic.ttf
          weight: 400
    - family: CascadiaCode
      fonts:
        - asset: assets/fonts/CascadiaCode-VariableFont_wght.ttf
          weight: 600

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/rendcuentas.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/rendcuentas.png"
